# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

categories:
- Sequence Analysis
description: 'Raptor: pre-filter for querying very large collection'
long_description: 'Raptor: A fast and space-efficient pre-filter for querying very
  large collections of nucleotide sequences.'
name: raptor_seqan3
owner: sgssgene
