# SPDX-FileCopyrightText: 2006-2025 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2025 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Cleanup Cache

on:
  pull_request_target:
    types:
      - closed

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  cleanup:
    name: Cleanup Caches
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Cleanup
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge
        run: |
          cacheKeysForPR=$(gh cache list --ref $BRANCH --limit 100 --json id --jq '.[].id')
          for cacheKey in $cacheKeysForPR; do
              gh cache delete $cacheKey
          done

