# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Documentation

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - unlabeled
  workflow_dispatch:

concurrency:
  group: doc-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  SHARG_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  build:
    name: Documentation
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch' || github.event.label.name == 'lint'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: raptor
          fetch-depth: 2
          submodules: true

      - name: Install CMake
        uses: seqan/actions/setup-cmake@main
        with:
          cmake: 3.25.3

      - name: Install Doxygen
        uses: seqan/actions/setup-doxygen@main
        with:
          doxygen: 1.9.6

      - name: Configure tests
        run: |
          mkdir build
          cd build
          cmake ../raptor/test/documentation
          make -j2 download-cppreference-doxygen-web-tag

      - name: Run tests
        run: |
          cd build
          ctest . -j2 --output-on-failure
