name: Fortify

on:
  schedule:
    - cron: "0 8 * * SAT"
  workflow_dispatch:

concurrency:
  group: fortify-${{ github.ref }}
  cancel-in-progress: true

env:
  SHARG_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  build:
    name: ${{ matrix.name }} ${{ matrix.build_type }}
    runs-on: ubuntu-22.04
    timeout-minutes: 240
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Fortify"
            build_type: Release
            cxx_flags: "-fcf-protection=check"

          - name: "Fortify"
            build_type: Debug
            cxx_flags: "-fcf-protection=full"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: raptor
          fetch-depth: 1
          submodules: true

      - name: Setup toolchain
        uses: seqan/actions/setup-toolchain@main
        with:
          compiler: gcc-13
          use_actions_cache: false

      - name: Install CMake
        uses: seqan/actions/setup-cmake@main
        with:
          cmake: 3.18.4

      - name: Configure tests
        run: |
          mkdir build
          cd build
          cmake ../raptor/test/unit -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                                    -DCMAKE_CXX_FLAGS="-std=c++23 -fexceptions -g -grecord-gcc-switches -pipe -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -mtune=native -fasynchronous-unwind-tables -fstack-clash-protection -Wno-interference-size ${{ matrix.cxx_flags }}"
          make -j2 gtest_build

      - name: Build tests
        run: |
          cd build
          make -k -j2

      - name: Run tests
        run: |
          cd build
          ctest . -j2 --output-on-failure

