name: Misc

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - unlabeled
  workflow_dispatch:

concurrency:
  group: misc-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  SHARG_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch' || github.event.label.name == 'lint'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Snippet gcc12"
            cxx: "g++-12"
            cc: "gcc-12"
            cxx_flags: "-std=c++23"
            build_type: Release
            build: snippet
            build_threads: 2
            test_threads: 2
            cmake: 3.18.4
            requires_toolchain: true
            requires_ccache: true
            skip_build_tests: false
            skip_run_tests: false

          - name: "Performance gcc12"
            cxx: "g++-12"
            cc: "gcc-12"
            cxx_flags: "-std=c++23"
            build_type: Release
            build: performance
            build_threads: 2
            test_threads: 2
            cmake: 3.18.4
            requires_toolchain: true
            requires_ccache: true
            skip_build_tests: false
            skip_run_tests: false

          - name: "Documentation"
            build: documentation
            build_threads: 2
            test_threads: 2
            cmake: 3.18.4
            doxygen: 1.9.6
            requires_toolchain: false
            requires_ccache: false
            skip_build_tests: true
            skip_run_tests: false

          - name: "Header gcc12"
            cxx: "g++-12"
            cc: "gcc-12"
            cxx_flags: "-std=c++23"
            build_type: Release
            build: header
            build_threads: 2
            test_threads: 2
            cmake: 3.18.4
            requires_toolchain: true
            requires_ccache: true
            skip_build_tests: false
            skip_run_tests: true

          - name: "Header gcc11"
            cxx: "g++-11"
            cc: "gcc-11"
            cxx_flags: "-std=c++23"
            build_type: Release
            build: header
            build_threads: 2
            test_threads: 2
            cmake: 3.18.4
            requires_toolchain: true
            requires_ccache: true
            skip_build_tests: false
            skip_run_tests: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: raptor
          fetch-depth: 2
          submodules: true

      - name: Add package source
        run: bash ./raptor/lib/seqan3/.github/workflows/scripts/configure_apt.sh

      - name: Install CMake
        env:
          BUILD: ${{ matrix.build }}
          CMAKE_VERSION: ${{ matrix.cmake }}
        run: bash ./raptor/lib/seqan3/.github/workflows/scripts/install_cmake.sh

      - name: Install Doxygen
        if: matrix.build == 'documentation'
        env:
          DOXYGEN_VERSION: ${{ matrix.doxygen }}
        run: bash ./raptor/lib/seqan3/.github/workflows/scripts/install_doxygen.sh

      - name: Install ccache
        if: matrix.requires_ccache
        run: sudo apt-get install --yes ccache

      - name: Install compiler ${{ matrix.cxx }}
        if: matrix.requires_toolchain
        run: sudo apt-get install --yes ${{ matrix.cxx }}

      - name: Load ccache
        if: matrix.requires_ccache
        uses: actions/cache@v3
        with:
          path: .ccache
          key: ${{ matrix.name }}-ccache-${{ github.ref }}-${{ github.run_number }}
          # Restoring: From current branch, otherwise from base branch, otherwise from any branch.
          restore-keys: |
            ${{ matrix.name }}-ccache-${{ github.ref }}
            ${{ matrix.name }}-ccache-${{ github.base_ref }}
            ${{ matrix.name }}-ccache-

      - name: Tool versions
        run: |
          env cmake --version
          env doxygen --version || true
          env ${{ matrix.cxx }} --version || true

      - name: Configure tests
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
        run: |
          mkdir build
          cd build
          cmake ../raptor/test/${{ matrix.build }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                                                   -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }} -Wno-interference-size" \
                                                   -DRAPTOR_NATIVE_BUILD=OFF
          case "${{ matrix.build }}" in
            snippet) make -j${{ matrix.build_threads }} gtest_build;;
            performance) make -j${{ matrix.build_threads }} gbenchmark_build;;
            header) make -j${{ matrix.build_threads }} gtest_build gbenchmark_build;;
            documentation) make -j${{ matrix.build_threads }} download-cppreference-doxygen-web-tag;;
          esac

      - name: Build tests
        if: ${{!matrix.skip_build_tests}}
        env:
          CCACHE_BASEDIR: ${{ github.workspace }}
          CCACHE_DIR: ${{ github.workspace }}/.ccache
          CCACHE_COMPRESS: true
          CCACHE_COMPRESSLEVEL: 12
          CCACHE_MAXSIZE: 150M
          CCACHE_IGNOREOPTIONS: "-fprofile-abs-path"
          CMAKE_BUILD_PARALLEL_LEVEL: ${{ matrix.build_threads }}
        run: |
          ccache -z || true
          cd build
          make -k -j2
          ccache -sv || true

      - name: Run tests
        if: ${{!matrix.skip_run_tests}}
        run: |
          cd build
          ctest . -j${{ matrix.test_threads }} --output-on-failure
