# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: macOS

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - unlabeled
  workflow_dispatch:

concurrency:
  group: macos-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  SHARG_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: macos-12
    timeout-minutes: 120
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch' || github.event.label.name == 'lint'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "gcc13"
            compiler: "gcc-13"
            build: unit
            build_type: Release
            cxx_flags: "-std=c++23"

          - name: "gcc12"
            compiler: "gcc-12"
            build: unit
            build_type: Release
            cxx_flags: "-std=c++23"

          - name: "gcc11"
            compiler: "gcc-11"
            build: unit
            build_type: Release
            cxx_flags: "-std=c++23"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: raptor
          fetch-depth: 2
          submodules: true

      - name: Setup toolchain
        uses: seqan/actions/setup-toolchain@main
        with:
          compiler: ${{ matrix.compiler }}
          ccache_size: 150M

      - name: Install CMake
        uses: seqan/actions/setup-cmake@main
        with:
          cmake: 3.25.3

      - name: Configure tests
        run: |
          mkdir build
          cd build
          cmake ../raptor/test/${{ matrix.build }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                                                   -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }} -Wno-interference-size" \
                                                   -DHIBF_NATIVE_BUILD=OFF
          make -j2 gtest_main

      - name: Build tests
        run: |
          ccache -z
          cd build
          make -k -j3
          ccache -sv

      - name: Run tests
        run: |
          cd build
          ctest . -j3 --output-on-failure
