name: macOS

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - unlabeled
  workflow_dispatch:

concurrency:
  group: macos-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  CMAKE_VERSION: 3.18.4
  SHARG_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: macos-12
    timeout-minutes: 120
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch' || github.event.label.name == 'lint'
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: "gcc13"
            cxx: "g++-13"
            cc: "gcc-13"
            build: unit
            build_type: Release
            cxx_flags: "-std=c++20"

          - name: "gcc12"
            cxx: "g++-12"
            cc: "gcc-12"
            build: unit
            build_type: Release
            cxx_flags: "-std=c++23"

          - name: "gcc11"
            cxx: "g++-11"
            cc: "gcc-11"
            build: unit
            build_type: Release
            cxx_flags: "-std=c++23"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: raptor
          fetch-depth: 2
          submodules: true

      - name: Configure Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install CMake
        run: bash ./raptor/lib/seqan3/.github/workflows/scripts/install_cmake.sh

      - name: Install ccache
        run: bash ./raptor/lib/seqan3/.github/workflows/scripts/install_via_brew.sh ccache

      - name: Install compiler ${{ matrix.cxx }}
        run: bash ./raptor/lib/seqan3/.github/workflows/scripts/install_via_brew.sh gcc $(echo "${{ matrix.cxx }}" | sed "s/g++-//g")

      - name: Load ccache
        uses: actions/cache@v3
        with:
          path: .ccache
          key: ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.ref }}-${{ github.run_number }}
          # Restoring: From current branch, otherwise from base branch, otherwise from any branch.
          restore-keys: |
            ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.ref }}
            ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.base_ref }}
            ${{ runner.os }}-${{ matrix.name }}-ccache-

      - name: Tool versions
        run: |
          env cmake --version
          env ${{ matrix.cxx }} --version
          sudo xcode-select -s '/Applications/Xcode_13.4.1.app/Contents/Developer' # https://github.com/actions/runner-images/issues/6350

      - name: Configure tests
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
        run: |
          mkdir build
          cd build
          cmake ../raptor/test/${{ matrix.build }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                                                   -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }} -Wno-interference-size" \
                                                   -DRAPTOR_NATIVE_BUILD=OFF
          make -j2 gtest_build

      - name: Build tests
        env:
          CCACHE_BASEDIR: ${{ github.workspace }}
          CCACHE_DIR: ${{ github.workspace }}/.ccache
          CCACHE_COMPRESS: true
          CCACHE_COMPRESSLEVEL: 12
          CCACHE_MAXSIZE: 150M
          CCACHE_IGNOREOPTIONS: "-fprofile-abs-path"
        run: |
          ccache -z
          cd build
          make -k -j3
          ccache -sv

      - name: Run tests
        run: |
          cd build
          ctest . -j3 --output-on-failure
